AWSTemplateFormatVersion : 2010-09-09
Description: >
  This template deploys set of basic resources shared between components.

  The following basic resources are predefined in this template:
  - infrastructure bucket
  - CodeStarConnection

# After creating the stack, the CodeStar Connection is in PENDING status by default.
# The OAuth handshake with the GitHub must be completed.
# See https://docs.aws.amazon.com/dtconsole/latest/userguide/connections-update.html for instructions.

Resources:
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: GitRepositoryConnection
      ProviderType: GitHub

  InfrastructureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ac-infrastructure-bucket-${AWS::AccountId}-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          -
            ExpirationInDays: 1
            Status: Enabled
            Transitions:
              -
                StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 0

  InfrastructureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InfrastructureBucket
      PolicyDocument:
        Statement:
          - Effect: Deny
            Action: "s3:*"
            Principal: "*"
            Resource:
              - !Sub  "${InfrastructureBucket.Arn}/*"
              - !GetAtt InfrastructureBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${InfrastructureBucket}
              - !Sub arn:${AWS::Partition}:s3:::${InfrastructureBucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: GrantCloudFormationFullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Role
          Value: pipeline-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            AWS:
              - !Ref AWS::AccountId
      Policies:
        - PolicyName: PipelineExecutionRolePermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource:
                  - !GetAtt CloudFormationExecutionRole.Arn
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:DescribeStackResource
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:GetObject*
                  - s3:PutObject*
                  - s3:GetBucket*
                  - s3:List*
                Resource:
                    - !Join [ '',[ !GetAtt InfrastructureBucket.Arn, '/*' ] ]
                    - !GetAtt InfrastructureBucket.Arn

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Role
          Value: aws-sam-pipeline-codebuild-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: CodeBuildLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
        - PolicyName: CodeBuildArtifactsBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource:
                  -
                    !Sub
                      - "${InfrastructureBucketArn}/*"
                      - InfrastructureBucketArn: !GetAtt InfrastructureBucket.Arn
        - PolicyName: AssumeStagePipExecutionRoles
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - sts:AssumeRole
                Effect: Allow
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:ResourceTag/Role: pipeline-execution-role
        - PolicyName: CodeBuildParameterStore
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/aspan-corporation/*"

  InfrastructureTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: ac-infrastructure-topic

  InfrastructureTopicPolicy:
    Type: AWS::SNS::TopicInlinePolicy
    Properties: 
      TopicArn: !Ref InfrastructureTopic
      PolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: CodeNotification_publish
            Effect: Allow
            Principal: 
              Service: codestar-notifications.amazonaws.com
            Action: sns:Publish
            Resource: !Ref InfrastructureTopic

Outputs:
  CodeStarConnectionArn:
    Description: The Arn of AWS CodeStar Connection used to connect to Aspan GitHub code repositories.
    Value: !Ref CodeStarConnection
    Export:
      Name: CodeStarConnectionArn

  InfrastructureBucketName:
    Description: The Arn of AWS CodeStar Connection used to connect to external code repositories.
    Value: !Ref InfrastructureBucket
    Export:
      Name: InfrastructureBucketName

  InfrastructureBucketArn:
    Description: The Arn of AWS CodeStar Connection used to connect to external code repositories.
    Value: !GetAtt InfrastructureBucket.Arn
    Export:
      Name: InfrastructureBucketArn

  CodeBuildServiceRoleArn:
    Description: The Arn of AWS CodeStar Connection used to connect to external code repositories.
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: CodeBuildServiceRoleArn

  InfrastructureTopicArn:
    Description: The Arn of the SNS topic used for infrastructure notifications.
    Value: !Ref InfrastructureTopic
    Export:
      Name: InfrastructureTopicArn

  CloudFormationExecutionRoleArn:
    Description: ARN of the IAM Role(CloudFormationExecutionRole)
    Value: !GetAtt CloudFormationExecutionRole.Arn
    Export:
      Name: CloudFormationExecutionRoleArn

  PipelineExecutionRoleArn:
    Description: ARN of the IAM Role(PipelineExecutionRole)
    Value: !GetAtt PipelineExecutionRole.Arn
    Export:
      Name: PipelineExecutionRoleArn
